dist: trusty
language: java
sudo: false
jdk:
  - openjdk8
cache:
  directories:
    - '$HOME/.m2/repository'
services:
  - docker
addons:
  sonarcloud:
    organization: "tango-controls" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN
jobs:
  include:
    - stage: build
      script: .travis/build.sh
    - stage: deploy
      name: "Deploy to SonarCloud"
      script:
        - .travis/build.sh
        - git fetch --unshallow --quiet
        - sonar-scanner -Dsonar.projectKey=org.tango-controls:TangoWebapp -Dsonar.sources=. -Dsonar.exclusions=build/**,jmvc/**,docs/**,apps/**
    -
      name: "Deploy to Amazon cloud"
      script:
        - .travis/build.sh
        - mv build/distributions/waltz.war build/distributions/$TRAVIS_BRANCH.war
      deploy:
        - provider: script
          script: bash .travis/deploy.sh
          skip_cleanup: true
          on:
            all_branches: true
    -
      name: "Deploy to GitHub releases"
      script: .travis/build.sh
      deploy:
        - provider: releases
          prerelease: true
          api_key: $GITHUB_OAUTH_TOKEN
          file: "build/distributions/waltz.war"
          skip_cleanup: true
          on:
            tags: true
    -
      name: "Deploy to docker hub"
      env:
        - REGISTRY_USER=ingvord DOCKER_IMAGE=tangocs/waltz
      script:
        - .travis/build.sh
        - docker build --pull --tag "$DOCKER_IMAGE" .
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        - docker tag "$DOCKER_IMAGE" "$DOCKER_IMAGE:$TRAVIS_BRANCH"
      deploy:
        - provider: script
          script: docker push "$DOCKER_IMAGE:latest"
          on:
            branch: master
        - provider: script
          script: docker push "$DOCKER_IMAGE:$TRAVIS_TAG"
          on:
            tags: true