language: java
sudo: false
addons:
  sonarcloud:
    organization: "tango-controls" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN
script:
  - chmod 777 ./jmvcc
  - gradle prepareWar
after_success:
  - sonar-scanner
jdk:
  - openjdk8
cache:
  directories:
    - '$HOME/.m2/repository'
