version: '3.7'

services:
  epics-sim:
    image: lnlssol/epics-sim
    entrypoint: /root/runIocsFG.sh
  tango-db:
    image: tangocs/mysql:9.2.2
    ports:
    - "9999:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
  tango-cs:
    image: ingvord/tango-cs-with-rest
    ports:
    - "10000:10000"
    - "10001:10001"
    environment:
    - TANGO_HOST=localhost:10000
    - MYSQL_HOST=tango-db:3306
    - MYSQL_USER=tango
    - MYSQL_PASSWORD=tango
    - MYSQL_DATABASE=tango
    depends_on:
    - tango-db
  tango-test:
    image: tangocs/tango-test
    environment:
    - TANGO_HOST=tango-cs:10000
    depends_on:
    - tango-cs
  tango-epics:
    image: ingvord/tango-epics
    environment:
    - TANGO_HOST=tango-cs:10000
    depends_on:
    - tango-cs
    - epics-sim
  waltz:
    image: tangocs/waltz:v0.7.3
    ports:
      - "8080:8080"